### ISSUE TITLE
[Bug]apimachinery can't shutdown gracefully

### ISSUE THREAD

**Issue by kaisawind** [cloustone/pandas#2]
The service can't shutdown when you press `Ctrl+C`, unless you shutdown the shell or bash.

**Comment by kaisawind** [comment]
WIP

**Comment by cloustone** [comment]
stop channel can not be used after http serving.
https://github.com/cloustone/pandas/commit/be822cbc44168043a8c1bc1ccbf8aba4cb133e2b
